### ISSUE TITLE
ImportError: No module named bitmex

### ISSUE THREAD

**Issue by tanzeelrana** [IlyaKrotov/BitMEX-simple-trading-robot#6]
tanzeel@tanzeel-HP-Compaq-dx7500-SFF:~/BitMEX-simple-trading-robot$ python main_loop.py 
Traceback (most recent call last):
  File "main_loop.py", line 1, in <module>
    import bitmex
ImportError: No module named bitmex

**Comment by tanzeelrana** [comment]
```
tanzeel@tanzeel-System-Product-Name:~/BitMEX-simple-trading-robot$ python main_loop.py 
Traceback (most recent call last):
  File "main_loop.py", line 1, in <module>
    import bitmex
  File "/home/tanzeel/.local/lib/python2.7/site-packages/bitmex.py", line 5, in <module>
    from BitMEXAPIKeyAuthenticator import APIKeyAuthenticator
  File "/home/tanzeel/.local/lib/python2.7/site-packages/BitMEXAPIKeyAuthenticator.py", line 1, in <module>
    import urllib.parse
ImportError: No module named parse
tanzeel@tanzeel-System-Product-Name:~/BitMEX-simple-trading-robot$ 

```
