### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by tanzeelrana** [IlyaKrotov/BitMEX-simple-trading-robot#7]
```
tanzeel@tanzeel-HP-Compaq-dx7500-SFF:~/BitMEX-simple-trading-robot$ python3 main_loop.py 
Traceback (most recent call last):
  File "main_loop.py", line 7, in <module>
    from trader import Trader
  File "/home/tanzeel/BitMEX-simple-trading-robot/trader.py", line 12
    print(f"Last prediction: {prediction}")
                                         ^
SyntaxError: invalid syntax
tanzeel@tanzeel-HP-Compaq-dx7500-SFF:~/BitMEX-simple-trading-robot$ 
```

**Comment by IlyaKrotov** [comment]
This problem occurs because of the old python3 version.
